In [1]:
import pandas as pd
df = pd.read_csv("https://github.com/loverberg/skillsDS/raw/main/hh.csv")

In [2]:
df

           Ids  ...                                        Description
0     49832475  ...  Компания DataFork — специалист в области обраб...
1     50505617  ...  Компания Wunder Fund ищет Python разработчика ...
2     48927705  ...  Мы создаем платформу данных для розничного биз...
3     50609648  ...  ANYCLASS - крупнейшая EdTech компания в сфере ...
4     50244485  ...  Студия MS-1, разрабатывающая легендарную мобил...
...        ...  ...                                                ...
1229  50154642  ...  Emma is the app to manage all things money. Ou...
1230  49970280  ...  Partners in Performance is a global management...
1231  49909656  ...  Команда проекта «Цифровой ассистент Робот Макс...
1232  47686394  ...  AppFollow is an application management platfor...
1233  49900574  ...  О компании: Компания-разработчик финтех ПО ище...

[1234 rows x 10 columns]